sudo: required
sevices:
    - docker
before_install:
    - docker build -t sean/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true sean/react-test npm test -- --coverage

after_success:
    - docker build -t seanshen20/multi-client ./client
    - docker build -t seanshen20/multi-nginx ./nginx
    - docker build -t seanshen20/multi-server ./server
    - docker build -t seanshen20/multi-worker ./worker
# Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# take images and push them to docker hub
    - docker push seanshen20/multi-client
    - docker push seanshen20/multi-nginx
    - docker push seanshen20/multi-server
    - docker push seanshen20/multi-worker
